### ISSUE TITLE
broken dependencies in configuration

### ISSUE THREAD

**Issue by tbe** [hardkernel/linux#105]
There are multiple broken dependencies. If backports is disabled the kernel build failes with

```
net/core/dev_ioctl.c:562: undefined reference to `wext_handle_ioctl' 
```

**Comment by mdrjr** [comment]
This is not an issue, this is how backports works. It replaces parts of the kernel with more recent parts.

**Comment by tbe** [comment]
No, this is not how backports work. It should be hard enabled if any option needs it.

My device will never get a wireless interface. But i have to enable and build it, or i figure out which option needs it. There is a reason why the kernel has such a complex configuration system.

**Comment by tobetter** [comment]
This couldn't be fixed in HK's branch since we should keep to support WiFi dongle #3 and #4. If you like to fix the error, you should fix it on your local branch only while maintain CONFIG_WEXT option.

**Comment by tbe** [comment]
I don't understand your point. The fix would be to fix the dependencies in the Kconfig files, not to drop any code or disable any support.

In `include/net/wext.h`  `wext_handle_ioctl` gets replaced with a stub function if `CONFIG_WEXT_CORE` is not set. If i disable the backports but keep `CONFIG_WEXT_CORE` enabled, i get the linker error. This is clearly solvable by checking for enabled backports in `include/net/wext.h` or make `CONFIG_WEXT_CORE` selecting the backports by adding `select BACKPORT_INTEGRATE` to `WEXT_CORE` in the correct Kconfig

**Comment by tobetter** [comment]
Sorry, I would misunderstand your previous post. Your approach would be reasonable, I would try.
