### ISSUE TITLE
Support overlayfs

### ISSUE THREAD

**Issue by paralin** [hardkernel/linux#114]
Would it be possible to merge in overlayfs support?

https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt

Thanks!
Christian

**Comment by mdrjr** [comment]
We support AUFS.

**Comment by paralin** [comment]
aufs and overlayfs are two different things, though, right?

**Comment by mdrjr** [comment]
Both are union fs'es and docker and use any of those.
Google for it and some results says that aufs is faster.

**Comment by paralin** [comment]
Alright, I'll just use aufs then. Thanks.
