### ISSUE TITLE
What is the latest compatible xu3 kernel release?

### ISSUE THREAD

**Issue by luckcolors** [hardkernel/linux#130]
Hello.
I really need to know what is the latest release for odroid xu3.
Because my friend currently has installed debian-odroid-Xu4 on his odroid-xu3 and it seems to get mac address an ip changed on every reboot, even if they were configured statically.(Maybe is there a way to fix this?) anyway kernel downgrade may fix this.
Thanks in advance.

**Comment by Obihoernchen** [comment]
last stable (official) release is 3.10.y: https://github.com/hardkernel/linux/tree/odroidxu3-3.10.y
4.2.y is still in development.

**Comment by luckcolors** [comment]
Ok Thanks! :)
