### ISSUE TITLE
Filesystem label corruption

### ISSUE THREAD

**Issue by paralin** [hardkernel/linux#133]
We're noticing this problem lately. Using an odroid xu3 (fresh board) on a SD card (and also seen on an MMC). Using ARM (little endian), ELF binaries, cortex-a15 build configuration, EABIhf (as opposed to just EABI), and NEON/VFPv4 instructions with Thumb2. 

Please let me know if any of those are not compatible.

The filesystem label seems to be corrupted in rare cases. It will be set to "layer", then on the next boot be "lager" or "la{ev". This seems like a bit flip via a timing error. Could this be caused by anything in the kernel?

This is using commit ID 30cd82480f257905c418b32735425585b15cebdd on the odroidxu3-3.10.y branch.

**Comment by paralin** [comment]
Any ideas about this? We compile for the A15 using: aacps-linux, cortex-15, vfp4-d16, hard, and arm

**Comment by mdrjr** [comment]
Sorry but I can't reproduce this issue. 
Over the last year I have several XU3/XU4 running 24/7 as build boxes for me.
They have been rock-solid and even taking some bad power outages I don't have any corruption.
