### ISSUE TITLE
f2fs backport

### ISSUE THREAD

**Issue by zehome** [hardkernel/linux#14]
I've done an f2fs backport on 3.0.y. It's available on https://github.com/zehome/linux/tree/odroid-3.0.y-f2fs

I don't know if you are interested in merging such a backport. If you are I can make a clean pull-request. Let me know ;)

**Comment by zehome** [comment]
(f2fs taken from latest 3.8 rc4 kernel)

**Comment by mdrjr** [comment]
I would love a PR for that ;) Really worth trying. There's alot of fuzz around that f2fs from Samsung.

**Comment by zehome** [comment]
Ok, that was kind of easy to port. Was my first backport on linux ever.. about 4 hours of work for a linux newbie like me :)

**Comment by hardkernel** [comment]
I merged your backport on odroid-3.0.y . 
Please close this issue.
