### ISSUE TITLE
EDID 1366x768.bin

### ISSUE THREAD

**Issue by tjjh89017** [hardkernel/linux#142]
Cloud you guys support for 1366x768 resolution for Linux 3.10 for ODROID-XU4?
Thanks. My TV's resolution is in 1366x768.
Thanks a lot

**Comment by mdrjr** [comment]
Just connecting it without anything it won't work?

**Comment by tjjh89017** [comment]
My TV didn't support it. So if I comment on all settings, it will set the resolution to 1280x720.
And it seems it can't use `xrandr` to force the resolution to 1366x768. It will just back to 1280x720.

**Comment by cburlacu** [comment]
I have same problem. My TV supports 1366x768, with 1280x720 is flickering...

**Comment by clehner** [comment]
The 1366x768 setting worked for me in ubuntu-16.04.2-minimal-odroid-xu4-20170516.img.xz on an ODROID-XU4 with a pi-top display. http://odroid.com/dokuwiki/doku.php?id=en:xu4_ubuntu_minimal

Edit: actually, the right half of the screen flickers - I think this display actually needs the "reduced blanking" setting, like [hdmi_mode=86 vs hdmi_mode=81](http://elinux.org/RPi_Configuration) which is what fixed that problem for me on the Raspberry Pi 3.
