### ISSUE TITLE
Arch linux-odroid-c1-3.10.80-16 <> linux-firmware

### ISSUE THREAD

**Issue by jeanmarc77** [hardkernel/linux#143]
Hello,
I notice that my FTDI converter hang after few minutes with the latest -16 build, dmesg return ftdi_sio ttyUSB0: failed to get modem status: -110. 
I have to downgrade to Arch linux-odroid-c1-3.10.80-14 where linux-firmware-20150904.6ebf5d5-1-any.pkg.tar.xz work without any hitch.
Thanks for your work

**Comment by mdrjr** [comment]
Wrong repo... https://github.com/archlinuxarm

**Comment by moonman** [comment]
Just some input on this: nothing changed on our side except for inclusion of CONFIG_MESON_GIC_FIQ=y in 3.10.80-16 package
My guess is that something broke between Oct 13th commit and now as most of the commits since Oct13th are dealing with USB and FIQ
