### ISSUE TITLE
New RTL8153 driver is causing page allocation failure

### ISSUE THREAD

**Issue by arter97** [hardkernel/linux#146]
https://github.com/arter97/odroid/commit/eb209c83dc57cca52423d85d87d3422b9affad81

This is on XU4.
Any comments?

(btw, there's a typo on http://www.hardkernel.com/main/products/prdt_info.php?g_code=G143452239825 which indicates RTL8153 as RTL8135.)

**Comment by Obihoernchen** [comment]
Is there a way to reproduce this?

Uptime is 8 days and I do not have such an error.

**Comment by arter97** [comment]
I'm not entirely sure.
I got those messages starting from uptime 3326 seconds(that's what I got from /var/log/syslog.1, /proc/kmsg is truncated), with interval something like 100 seconds for each of those "page allocation failure" log.

My XU4 is constantly under network stress.
Dozens of people are always simultaneously downloading multiple files from USB 3.0 connected SSD, easily exceeding 100 Mbps in total.
Maybe that's why I've encountered that issue. And since downtime or any issues with my XU4 is critical, I recompiled the kernel with that commit reverted immediately after I saw those. Now the issue is gone(uptime 8000 seconds).

While I did not encounter any weirdness something like SSH connection loss, I don't know if any people might have experienced connection loss or data damage while downloading files.

**Comment by moonman** [comment]
Mine has been rock solid since I tested this (Before it was committed to this repo). I have a lot of stuff running on my xu4 including http server that serves files + samba server. Http traffic exceeds 80GB/day sometimes. + sometimes hundreds of gigabytes over local network. It's been up for a month.

**Comment by arter97** [comment]
XU3?
Does it use 8153?

**Comment by mdrjr** [comment]
No, XU3 uses another adapter.

**Comment by arter97** [comment]
Then is he using USB external ethernet powered by 8153?

**Comment by moonman** [comment]
Sorry, I meant XU4 (post above fixed). I don't have XU3, but all kernels, images etc. use that name so it was stuck in my head :)

**Comment by arter97** [comment]
So you have no complainings on the kmsg with a month of uptime?

**Comment by moonman** [comment]
No, I've got nothing at all. Just came back from a 2 week vacation and was using XU4 for VPN all the time. I really don't know what's up. It may be that the board is no receiving enough traffic. What distro are you using and what kernel? I'm on archlinuxarm.

**Comment by arter97** [comment]
Ubuntu 15.04 provided by hardkernel and custom kernel, from that Git mentioned above.
And yea, it's "custom" kernel, but I don't think it's the problem at my end as downgraded drivers are working perfectly fine.

**Comment by arter97** [comment]
Oh darn, seems like it's a problem at my end as I reproduced the same error with downgraded version.
Googling tells me to adjust vm kernel parameters.

Sorry!
