### ISSUE TITLE
rtl8192 troubles

### ISSUE THREAD

**Issue by RcrdBrt** [hardkernel/linux#154]
"odroid wifi adapter 3" has a very strange behavior: it works perfectly fine with 4.3.3 kernel build of raspberry pi 2, with 4.3.3 kernel of my PC (stock archlinux kernel + BFQ) and 4.1.15 (LTS).
I'm getting big performance hit with the odroid C1+ rev0.4 20150930 (both with ping and the download speed of about 1Mbit/s when I achieve 16-17Mbit/s with the same dongle on other devices), though. I tried:
1) using the official v2.2 android 4.4.2 build;
2) using the official lxde ubuntu image;
3) dkms build of the 8192cu on archlinux;
4) stock rtl8192cu of odroid c1 branch here;
5) disabling the power management of one module at a time (rtl8192cu and 8192cu), either via modprobe.d/ conf and via pm-utils. No success;
6) changing USB ports of odroid (I was thinking about a USB malfunction since I struggle to find the reasons for my problems);
7) surfing the web: I found many threads in yours and archlinuxarm forums in which they were complaining about the "wifi dongle 3" issue years ago (2014). It seems to them you have fixed up the things at some point for a bunch of users. And then the troubles returned in 2015 with a fluctuating behavior between users who found workarounds and users who never got it sorted. You were never able to reproduce the issue in your office, though. But I can assure you there is a situation here;
8) ethernet. That one works like a charm;
9) another rtl8188cus dongle (low profile one, without antenna). it has the exact same behavior, again, no success;
10) I don't have any more dongles to try, but if you suggest me that an ath9k dongle works great in 100% of the users, I could buy that to replace your official one (I read threads of people having troubles also with that in your forums, but they are dated and not so many as the 8188cus ones).

The thing is that in the most similar device I have (raspberry pi 2) the dongle is actually great and the module shows the exact same driver version of the odroid C1 branch (v4.0.2_9000.20130911), just a different srcversion string.

I got rid of my initial project of making the odroid c1+ an android TV device for this reason. It's a pretty good device and it's a shame. I really hope for an investigation of the issue and a final fix.
Thanks for the reading.

**Comment by mdrjr** [comment]
root@odroid:~# lsusb
Bus 001 Device 003: ID 0bda:8178 Realtek Semiconductor Corp. RTL8192CU 802.11n WLAN Adapter

root@odroid:~# uname -a
Linux odroid 3.10.80-125 #1 SMP PREEMPT Wed Sep 2 04:22:11 BRT 2015 armv7l armv7l armv7l GNU/Linux

---

Client connecting to X, TCP port 5001

## TCP window size: 85.3 KByte (default)

[  3] local X port 51733 connected with X port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  88.8 MBytes  74.4 Mbits/sec
[  3] 10.0-20.0 sec  92.5 MBytes  77.6 Mbits/sec
[  3] 20.0-30.0 sec  95.2 MBytes  79.9 Mbits/sec
[  3] 30.0-40.0 sec   101 MBytes  84.8 Mbits/sec
[  3] 40.0-50.0 sec  99.6 MBytes  83.6 Mbits/sec
[  3] 50.0-60.0 sec  98.0 MBytes  82.2 Mbits/sec
[  3] 60.0-70.0 sec  97.9 MBytes  82.1 Mbits/sec
[  3] 70.0-80.0 sec  97.8 MBytes  82.0 Mbits/sec
[  3] 80.0-90.0 sec  97.1 MBytes  81.5 Mbits/sec
[  3] 90.0-100.0 sec  98.8 MBytes  82.8 Mbits/sec
[  3] 100.0-110.0 sec  99.0 MBytes  83.0 Mbits/sec
[  3] 110.0-120.0 sec   112 MBytes  94.0 Mbits/sec
[  3] 120.0-130.0 sec   101 MBytes  84.7 Mbits/sec
[  3] 130.0-140.0 sec   103 MBytes  86.1 Mbits/sec
[  3] 140.0-150.0 sec  88.1 MBytes  73.9 Mbits/sec
[  3] 150.0-160.0 sec  86.6 MBytes  72.7 Mbits/sec
[  3] 160.0-170.0 sec  91.6 MBytes  76.9 Mbits/sec
[  3] 170.0-180.0 sec  99.9 MBytes  83.8 Mbits/sec
^C[  3]  0.0-188.7 sec  1.79 GBytes  81.7 Mbits/sec

You should check the drivers on whatever you are testing.. I can keep stable 80Mbit/s average.
