### ISSUE TITLE
3.10.y C1 kernel - console mode screen corruption

### ISSUE THREAD

**Issue by MagaTailor** [hardkernel/linux#158]
Ever since kernel rev. `138`, the lower `1/3` of the screen in console sxga mode (dvi) is plain grey meaning the terminal you can type in ends at the cutoff point.

There are no visual glitches in X. Last working revision == `135`.

**Comment by mdrjr** [comment]
Hello,

I've tested here on my side and using DVI and 1280x1024 and its all good console and X11.

**Comment by MagaTailor** [comment]
Strange, maybe it's related to the update script somehow? (I remember a problem with missing slashes in boot.ini after an update)

X was never affected, just the console. Do you suspect what could have happened?
BTW, on my side VPU is disabled and colour depth is @ 16bpp.

-original message-
Subject: Re: [linux] 3.10.y C1 kernel - broken console DVI resolution (#158)
From: Mauro Ribeiro notifications@github.com
Date: 05.02.2016 08:29

Hello,

I've tested here on my side and using DVI and 1280x1024 and its all good console and X11.

---

**Comment by MagaTailor** [comment]
Ok, it's definitely related to video memory content. Booting to to the console (no X) looks like this:
- @ 16bpp, the grey bar is present from the beginning
- @ 24 bpp, it's normal until login prompt appears, then the corruption starts just as above
- @ 32 bpp, behaves like above, but instead of the grey bar it's showing the original boot messages that were present in that part of the screen.

At 24 or 32bpp, starting X and switching to the console (Alt+F*) fills the the top quarter of the bar with corrupted contents of the bottom part of the X screen.

I repeat, this stuff started after `135` and is there to this day. What's the reason `uInitrd` size went from 2.5MB to 6MB after `135`? (which happens to coincide with this issue.)

**Comment by mdrjr** [comment]
oh! That's booting to console... 
I'll check that.. My board was booting to X11 and I was switching to console.

**Comment by tokazio** [comment]
no screen in hdmi for me. with headless ubuntu since ive updated the kernel. black screen sometimes with white lines blinking from top to bottom.

**Comment by MagaTailor** [comment]
It seems stopping `lightdm` from `tty` (but not xterm) fixes that particular terminal but other tty's stay broken.
