### ISSUE TITLE
IPV6_SUBTREES not enabled in kernel

### ISSUE THREAD

**Issue by dtaht** [hardkernel/linux#177]
I was hoping to use these boxes as a test platform for some outputs of the ietf "homenet" working group.

One mandatory feature (source specific routing) is enabled best by having the IPV6_SUBTREES option enabled. Could I coax you to turn that on in your default builds for the c1,c2, etc? (the c2, especially)

https://tools.ietf.org/wg/homenet/

**Comment by JoshDi** [comment]
I have added this option to my fork: https://github.com/JoshDi/linux/tree/odroidc2-3.14.y

**Comment by dtaht** [comment]
Thank you! I am sufficiently boring to just want to download a new
kernel deb for further testing. Do you make those also?

The relevant thread is over on the babel-users mailing list:

http://lists.alioth.debian.org/pipermail/babel-users/2016-March/thread.html

As a side note is there work ongoing on getting up to say, kernel 4.4?

**Comment by JoshDi** [comment]
I believe odroid is working on a release schedule for v4.4.
