### ISSUE TITLE
Had to Revert Commit #7bf1d5f due to Ethernet connectivity issues and SD card R/W corruption.

### ISSUE THREAD

**Issue by wrxtasy** [hardkernel/linux#187]
Had to revert this Commit due to numerous SD card R/W errors. All brands.
LibreELEC was consequently unusable. This commit works find for eMMC cards though.

> [ 143.481823] aml_sd_emmc_data_thread 2211 sd: cmd:13
> [ 143.481833] mmcblk0: error -110 sending status command, aborting
> [ 143.481841] blk_update_request: 7 callbacks suppressed
> [ 143.481845] end_request: I/O error, dev mmcblk0, sector 1052676
> [ 143.481854] Buffer I/O error on device mmcblk0p2, logical block 2
> [ 143.481858] lost page write due to I/O error on mmcblk0p2
> [ 143.481889] [aml_sd_emmc_irq] sd: resp_timeout,vstat:0x800,virqc:3fff

**Comment by paralin** [comment]
Hmm any ideas why?

**Comment by bkrepo** [comment]
We need the more specific information of the SD card which has this error. Please give the url link of the SD card in order to test it.

**Comment by wrxtasy** [comment]
A follow up to the problem I was having.  Turned out to be a SD card reader Hardware issue on the dev. board I had.  The Retail C2's I now have do not have this problem.
