### ISSUE TITLE
archlinux kernel 3.14.29 with gcc6 error

### ISSUE THREAD

**Issue by mrdevis** [hardkernel/linux#198]
Hi,
Trying to compile the 3.14.29 kernel from this repository on an Odroid C2 with a fresh archlinux install (and therefore using gcc6) gives me this error::

`
    In file included from include/linux/compiler.h:54

```
from include/uapi/linux/stddef.h:1,

from include/linux/stddef.h:4,

from /home/arch_sc/linux/include/uapi/linux/posix_types.h:4,

from include/uapi/linux/types.h:13,

from include/linux/types.h:5,

from include/linux/mod_devicetable.h:11,

from scripts/mod/devicetable-offsets.c:2:

include/linux/compiler-gcc.h:106:30: fatal error: linux/compiler-gcc6.h: No such file or directory`
```

I have found some remarks on this here [http://www.spinics.net/lists/kernel/msg2257497.html], but not yet a solution on how to patch this in. Any help much appreciated!

Thanks, Jeroen

**Comment by c3V6a2Vy** [comment]
I believe this is the [patch -- cb984d1](https://github.com/torvalds/linux/commit/cb984d101b30eb7478d32df56a0023e4603cba7f#diff-812970a619bb628cf869e2a4a9029ce5) from 4.2 kernel.

It just combines the old `compiler-gccx.h` files and should be able to just merged in.

**Comment by mrdevis** [comment]
Thanks! That did the trick!!
