### ISSUE TITLE
[ODROID C2] SWAPPING no longer working correctly on 3.14.65

### ISSUE THREAD

**Issue by meveric** [hardkernel/linux#204]
Ever since the update to 3.14.65 swapping (either ZRAM or regular SWAP) is no longer working correctly.
During compiling, if a lot of RAM is used, the system does no longer swap, even setting swappiness to 100 doesn't help at all.

Using 3.14.29 both ZRAM and SWAP are working correctly.

**Comment by bkrepo** [comment]
I also confirmed this issue. C2 Ubuntu cannot swap the memory without ZRAM configuration. 
I used [this test program](https://gist.github.com/bkrepo/f9b305e71ff79070ace18e057a7515b8). The program is always killed after allocating 1.3GB memory even if the swap free space is enough.

Thank you for the report. We will look into this problem.

**Comment by bkrepo** [comment]
This problem is due to unnecessary **_Low Memory Killer_**. Low memory killer is for Android memory management. Linux use **_OOM killer_** generally. The fixed patch will upload soon.

**Comment by meveric** [comment]
Thanks :)
Hope I can try and build a new package before I have to leave for vacation :)

**Comment by bkrepo** [comment]
Fixed at https://github.com/hardkernel/linux/commit/3dd584f4bfeee51c940374ef270d66adc576ee52.
