### ISSUE TITLE
About resolution change patches.

### ISSUE THREAD

**Issue by Readon** [hardkernel/linux#21]
I find the latest version for odroid 3.0.y removed all function about changing resolution on HDMI interface. 
Why it should be reverted? Does it works? Is there any unpairable problem on that?

**Comment by mdrjr** [comment]
It was reverted because its incomplete. We don't know if it will work.

**Comment by Readon** [comment]
Will you finish this in future?
or where does this patch come from?
How can I try and continue this work?

**Comment by mdrjr** [comment]
Yes, I'm working on it.
Comes from my head.
Apply those patchs and submit PR's here.
http://www.youtube.com/watch?v=OSWj4cVZK6E
Its a partial show of it running, also, you can contact me on irc #odroid @ Freenode

**Comment by Readon** [comment]
Command in this video could not be seen clearly. Would you please give it to me here?
