### ISSUE TITLE
C2: libvirt-bin does not start (Virt-Manager)

### ISSUE THREAD

**Issue by OtherCrashOverride** [hardkernel/linux#217]
With the current c2 kernel, virt-manager/virsh has stopped working.  I suspect it is related to this:
http://forum.odroid.com/viewtopic.php?f=136&t=18971&start=50#p133845
and the patch for it is here:
https://github.com/OtherCrashOverride/c2-merge-conflicts/blob/master/0001-aml_thermal-Do-not-rename-device.patch

**Comment by bkrepo** [comment]
Thank you for the report.
I also checked virt-manager is running or not depending on device_rename() line. The null string device name is bad naming. So, your patch is needed. 

Could you send PR with modifying the commit? (Please just delete the line)

**Comment by OtherCrashOverride** [comment]
Its faster if someone else does the change since its just removing a single line.  It will be later in the week before I could make a PR.

**Comment by mdrjr** [comment]
Hello @OtherCrashOverride I've merged your patch :) 
It will go live as soon as we release an kernel update. Thank you so much for all your contributions.
