### ISSUE TITLE
 odroidxu3-3.10.y-patch_3.10.93-rt101 with a black screen

### ISSUE THREAD

**Issue by chen0yi** [hardkernel/linux#257]
I compile RT Linux Preempt kernel with  odroidxu3-3.10.y-patch_3.10.93-rt101 ,there is no error, but when I reboot odroidxu4, there is a black screen. What is problem?

**Comment by bkrepo** [comment]
That's not our kernel. 
Go to the related forum thread: http://forum.odroid.com/viewtopic.php?f=95&t=25090
