### ISSUE TITLE
Kernel fails to build

### ISSUE THREAD

**Issue by declanmalone** [hardkernel/linux#26]
$ git clone --depth=1 https://github.com/hardkernel/linux.git -b odroid-3.0.y odroid-3.0.y
$ make odroidu2_ubuntu_mali_defconfig
$ make menuconfig (leave everything as is)
$ make zImage
fs/block_dev.c: In function ‘bdev_inode_switch_bdi’:
fs/block_dev.c:67:4: error: ‘wakeup_bdi’ undeclared (first use in this function)
fs/block_dev.c:67:4: note: each undeclared identifier is reported only once for each function it appears in
make[1]: **\* [fs/block_dev.o] Error 1
make[1]: **\* Waiting for unfinished jobs....

Result: No kernel built into arch/arm/boot/zImage

**Comment by mdrjr** [comment]
Fixed with commit 38098b1eb6b076bf3653a575f8360f027beeb9e4
