### ISSUE TITLE
CONFIG_USB_UAS & CONFIG_USB_STORAGE to module

### ISSUE THREAD

**Issue by matthuisman** [hardkernel/linux#290]
Having them as modules allows for forcing usb-storage mode using a modprobe.d rule

eg. 
/etc/modprobe.d/disable-uas.conf
`options usb-storage quirks=0x0bc2:0x3321:u`

Should help with these sort of issues:
https://forum.odroid.com/viewtopic.php?f=146&t=26016&start=50#p187838
https://forum.odroid.com/viewtopic.php?f=146&t=26016#p186301

**Comment by OtherCrashOverride** [comment]
This can be done on the kernel command line:
https://forum.odroid.com/viewtopic.php?f=146&t=26016&start=50#p188320

**Comment by matthuisman** [comment]
Thank you :)
I'll close the issue.

(Re-opens)
Actually, is there any "downside" to making these modules?
Personally I like using a modprob file instead of touching the kernel cmdline.

Also, a lot of the solutions online are the modprobe solution so a lot of users may try that first.

(Currently I use ArchLinux and have just modified the PKGBUILD to replace the Y with a M)

**Comment by OtherCrashOverride** [comment]
The down side to making it a module is that you need a initrd to use USB storage at boot time.  If the initrd is ever out of sync with the kernel, USB storage will not be accessible (rootfs on HDD, etc).  This also impacts those not using an initrd in embedded projects.

**Comment by matthuisman** [comment]
Thanks.
I'll close :)
