### ISSUE TITLE
odroid u2 poweroff failure

### ISSUE THREAD

**Issue by goniz** [hardkernel/linux#31]
running debian jessie powered by 3.8.13.14
using 8gb sdcard and a standard micro-hdmi to hdmi cable
typed in the terminal:

sudo bash
sync && poweroff

![img_20131221_233957](https://f.cloud.github.com/assets/976803/1845651/833e9a66-7597-11e3-9fc6-4d40a1c60140.jpg)

sources seem to point to this file:
vi arch/arm/mach-exynos/mach-hkdk4412.c +585

**Comment by mdrjr** [comment]
This is a known bug, switch the cpu governor to performance and try to reboot let me know the results

**Comment by goniz** [comment]
Thanks for the fast response.
Im afraid I will have access to my u2 as soon as the next weekend..
but if its a known issue then consider this as a duplicate
