### ISSUE TITLE
No rule to make target `firmware_install'

### ISSUE THREAD

**Issue by Chris-Bee** [hardkernel/linux#334]
Hello,
I'm using branch "odroidxu4-4.14.y" and try to install the firmware after compiling:
    make firmware_install
I get this error:
    make: *** No rule to make target `firmware_install'.  Stop.

There seems to be a patch (https://patchwork.kernel.org/patch/9960627/) but I don't see this kind of content in the file from this repository. Also, I worked with branch "odroidxu4-4.9.y" before and there it works just fine.

Best,
Chris

**Comment by mdrjr** [comment]
See: http://lkml.iu.edu/hypermail/linux/kernel/1709.1/04650.html

Support for firmware_install was dropped on 4.14
