### ISSUE TITLE
Problems with DVB stick on the usb bus. Solution: Patching softirq.c

### ISSUE THREAD

**Issue by saturn-hh** [hardkernel/linux#354]
Actually with the current sources I have problems with using DVB-Sticks on the USB bus. I get continuity errors and the stick is unusable.
Fortunatly this error is allready known and the  following patch is available:

https://raw.githubusercontent.com/armbian/build/master/patch/kernel/sunxi-next/linux-999-revert-softirq-let-ksoftirqd-do-its-job.patch
The patch  reverts a patch and is solving this issue.

Please aplay the patch to the sources for odroid xu4!

Explanation to the "bad" change in the kernel:
https://lwn.net/Articles/698807/

**Comment by f1vefour** [comment]
I'm not sure this is the right thing to do, this needs to be fixed upstream.

In the meantime you can use this patch and build your own kernel, while not ideal it is the proper thing.

**Comment by mdrjr** [comment]
Picked up with 10d20fd5644403895cf3d280194342f564e44f5e
