### ISSUE TITLE
rtl8192 issues in 3.8.13.16

### ISSUE THREAD

**Issue by brav0hax** [hardkernel/linux#36]
I recently compiled the new kernel for my odroid u2 and noticed my TPLink TL-WN823N usb wireless adapter stopped working. I went through the commits and found the following changes to the defconfig:
-CONFIG_RTL8192CU=m
-CONFIG_RTLWIFI=m
-CONFIG_RTLWIFI_DEBUG=y
-CONFIG_RTL8192C_COMMON=m
+# CONFIG_RTL8192CU is not set
+CONFIG_RTL8192CU_V40=m

I am not sure if its an issue with the wireless driver (v4.0) or if additional settings are missing. I tried to compile 3.8.13.16 with those settings and still didn't seem to work. Not sure what you could do, but though I'd let you know.

lsmod 3.8.13.14
Module                  Size  Used by
nfnetlink_log           7661  0 
nfnetlink               4106  1 nfnetlink_log
ipv6                  262878  24 
dm_crypt               14809  0 
dm_mod                 70048  1 dm_crypt
rtl8192cu              92885  0 
rtlwifi                78850  1 rtl8192cu
rtl8192c_common        59657  1 rtl8192cu
smsc95xx               19099  0 
usbnet                 19456  1 smsc95xx
gpio_keys               7070  0 

lsmod 3.8.13.16
Module                  Size  Used by
nfnetlink_log           7713  0 
nfnetlink               4090  1 nfnetlink_log
ipv6                  267433  26 
dm_crypt               14855  0 
rtl8192cu             521699  0 
smsc95xx               19079  0 
usbnet                 19408  1 smsc95xx
gpio_keys               7087  0 
dm_mod                 70172  1 dm_crypt

Thanks,
Eric

**Comment by brav0hax** [comment]
Correction to above. I used the original settings from 3.8.13.14 (changed kernel settings) and it worked fine. Its the v4.0 driver that seems to be messing things up.

**Comment by mdrjr** [comment]
what's the chipset from that dongle?

any error logs?

**Comment by brav0hax** [comment]
"The TL-WN823N WLAN USB stick bases on the Realtek chip set RTL8192CU and
provides a transmission rate up to 300Mbps."

From this site ->
http://www.linux-hardware-guide.com/2013-04-21-tp-link-tl-wn823n-mini-wireless-n-usb-300mbps

Sorry that is all I could find.

**Comment by mdrjr** [comment]
New kernel drivers show better stability :)
