### ISSUE TITLE
Kernel 4.14.81-151 wont compile with KVM enables

### ISSUE THREAD

**Issue by home42do** [hardkernel/linux#365]
Hi folks,
the spectre/meltdown patches seem to break KVM support.
Kernel 4.14.81-151.tar.gz  wont compile.
Build 4.14.69-148.tar.gz works well.

 CHK     include/generated/compile.h
  AS      arch/arm/mm/proc-v7.o
arch/arm/mm/proc-v7.S: Assembler messages:
arch/arm/mm/proc-v7.S:622: Error: symbol `cpu_ca15_switch_mm' is already defined
scripts/Makefile.build:429: recipe for target 'arch/arm/mm/proc-v7.o' failed
make[1]: *** [arch/arm/mm/proc-v7.o] Error 1
Makefile:1039: recipe for target 'arch/arm/mm' failed
make: *** [arch/arm/mm] Error 2
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.

Dierk

[config.txt](https://github.com/hardkernel/linux/files/2614372/config.txt)
[log.txt](https://github.com/hardkernel/linux/files/2614374/log.txt)

**Comment by mdrjr** [comment]
Does 4.14.83 builds ?

**Comment by home42do** [comment]
Hi Mauro,
also the actual kernel from https://github.com/hardkernel wont compile (same errors).
Appling patches 82 + 83 to the actual cloned kernel succeed, but the kernel also wont compile.


Kernels from original Linux repository compile but dont come up with kvm, because
the "cpu ist in wrong mode" when booting (no HYP mode). Code for adressing secure mode 
in the exynos cpu seems to be missing.

Dierk

**Comment by mdrjr** [comment]
Please try this patch and let me know if it works..


`diff --git a/arch/arm/mm/proc-v7-3level.S b/arch/arm/mm/proc-v7-3level.S
index cae6bb4..43bb86a 100644
--- a/arch/arm/mm/proc-v7-3level.S
+++ b/arch/arm/mm/proc-v7-3level.S
@@ -75,7 +75,7 @@ ENDPROC(cpu_v7_btbinv_switch_mm)
  *     Cortex-A15 requires ACTLR[0] to be set from secure in order
  *     for the icache invalidation to also invalidate the BTB.
  */
-ENTRY(cpu_ca15_switch_mm)
+/*ENTRY(cpu_ca15_switch_mm)
 #ifdef CONFIG_MMU
        mcr     p15, 0, r0, c7, c5, 0                   @ ICIALLU
        mmid    r2, r2
@@ -85,7 +85,7 @@ ENTRY(cpu_ca15_switch_mm)
        isb
 #endif
        ret     lr
-ENDPROC(cpu_ca15_switch_mm)
+ENDPROC(cpu_ca15_switch_mm) */
 
 #ifdef __ARMEB__
 #define rl r3
`

**Comment by mdrjr** [comment]
Please try this patch and let me know if it works

http://paste.ubuntu.com/p/bB8CfKbq55/

**Comment by home42do** [comment]
Hi Mauro,
the patch workeon both kernels (4.14.81 and 4.14.83) and the kernels now compile flawless.
When running these kernels everrything including KVM works fine.
Should be commited to source.
Dierk

**Comment by yrzr** [comment]
@mdrjr thanks, the patch works for me in #369
