### ISSUE TITLE
[odroidgoA-4.4.y] Issue with compiling DKMS modules

### ISSUE THREAD

**Issue by kamotswind** [hardkernel/linux#388]
The following URL describes the issue and the fix:
https://lkml.org/lkml/2016/3/31/720

Can merge this commit:
https://github.com/torvalds/linux/commit/962475ac2f9662fe69a9f86220ab31bbbf3911d2#diff-03db9657e7716d9ca27a586068430b37

**Comment by JeonghwaCho** [comment]
Hi Kamots,
The commit has been merged.
https://github.com/hardkernel/linux/commit/0060d908cc4ba21167d8cf00675518d18529b800

I've tested it as I mentioned in this forum thread.
https://forum.odroid.com/viewtopic.php?f=196&t=37432#p279027

But please confirm it by your side, and if you need me to update some, please let me know.
Or if you have no issue, please change this issue status.

**Comment by JeonghwaCho** [comment]
Hi Kamots,
Let's close this task.
