### ISSUE TITLE
HDMI might miss an IRQ on power off

### ISSUE THREAD

**Issue by claudiobsd** [hardkernel/linux#40]
The function hdmi_s_power() on hdmi_drv.c might miss the external IRQ trigger when powering off.
The function enables the external IRQ source which is triggered on EDGE. Some devices might set the signal in high before they are ready to negotiate a signal, and the board never goes into "plugged" state, since when the IRQ is enabled, the line is already high (no edge!).
The solution is to add:
queue_delayed_work(system_nrt_wq, &hdev->hpd_work_ext, 0);

immediately after the IRQ is enabled in hdmi_s_power(), to force the system to check if the signal is already high.

See this link for more details:

http://forum.odroid.com/viewtopic.php?f=73&t=3889#p32451

**Comment by mdrjr** [comment]
Closing this issue as you already submit a PR that fixes it :) 

In case.. the commit in question is -> 88e73bf450c1033aff19959dc978e526c21cb2ba
