### ISSUE TITLE
ODROID-HC4: control fan speed using tripping points (Debian)

### ISSUE THREAD

**Issue by mwip** [hardkernel/linux#408]
*Don't know if this is the right place. Unfortunately I wasn't able to sign up to the ODROID forum. Feel free to close if inappropriate.*

This thread on the ODROID Forum ([Odroid-HC4: Control Fan Speed?](https://forum.odroid.com/viewtopic.php?f=205&p=313651)) goes over how to adjust the fan speed when using UBUNTU. However, the suggested (and accepted) solution therein does not apply for the Debian version. I am not certain whether is is a Bug, or just a case of missing documentation. In the latter case I would of course be happy to review any changes to the [HC4  wiki](https://wiki.odroid.com/odroid-hc4/odroid-hc4) and test them.

Also I tested several other methods for e.g. the [XU4](https://www.hardkernel.com/blog-2/how-to-control-odroid-xu4-cooling-fan/) but was only able to activate manual mode, and that one also only briefly (2-3 secs). 

System Info: 
Hardware: ODROID-HC4
OS: Debian 10 installed from the Netboot loader.

**Comment by tobetter** [comment]
The thread you've referred is a bit outdated and based on Hardkernel's stock Linux kernel 4.9 but you are running upstream kernel which must be 5.9 or 5.10, the method of fan control between them are a bit different. Please refer to the link for the detail.
https://docs.linuxfactory.or.kr/guides/sensors.html#fanspeed-control

Also, in case if you like to customize the fan speed, please try to use the tool 'fancontrol'.

**Comment by mwip** [comment]
@tobetter thanks for pointing me to your docs. 

As you guessed, I am running kernel 5.10. 

I guess, that fancontrol is the better solution, as the with "automatic" doesn't ramp on the fan at all. That leaves me with ~53°C on "idle" (running Nexctcloudpi, yet no users active) and up to 75+ °C when running pbzip2 on a heavy workload over an extended period of time. I recon that these temps are not quite sustainable when running the system for multiple years, or are they?

However, fancontrol for is not documented for the HC4. Maybe we could collaborate on extending your docs on that (while extending beyond the HC4 horizon)

**Comment by tobetter** [comment]
The 'fancontrol' is the generic tool to customize the fan speed with given temperature and it's easy solution than touch sys node directly. But there is no documentation yet. It would be awesome if you test it and propose the pwm table to be applied for HC4. :D

**Comment by mwip** [comment]
Of course. I'll get back to you over on your docs repo. In the meantime, Ill leave this issue open.

**Comment by mwip** [comment]
Awesome. Thanks @tobetter for pointing me into the right direction. I think your docs are an awesome source of information, yet they are obscure to the new user. Perhaps you guys over at @hardkernel should add it to the official wiki or store page?
