### ISSUE TITLE
Which branch can i use to update my Odroid N2+?

### ISSUE THREAD

**Issue by apprehensivetarget** [hardkernel/linux#422]
I was wondering if i could update my kernel to a newer version as i am on  4.9.277-117, can i use any branch or not?

**Comment by tobetter** [comment]
If you like to use upstream kernel like 5.x, please do use my kernel branch.
https://github.com/tobetter/linux/tree/odroid-5.14.y

**Comment by apprehensivetarget** [comment]
Is there a difference to this repo?
