### ISSUE TITLE
LM75 temperature sensor module missing

### ISSUE THREAD

**Issue by marcominetti** [hardkernel/linux#46]
Hi, running sensors-detect from lm-sensors in ubuntu on Odroid U3, the LM75 Texas Instruments seems to be detected but the module lm75 is not available for the kernel.

Is it the correct module?

Could you include in kernel compile build script/config?

I'd like to hopefully use sensors command from lm-sensors...

**Comment by marcominetti** [comment]
From sensors-detect:

Driver `lm75':
- Bus `s3c2410-i2c'
  Busdriver`UNKNOWN', I2C address 0x49
  Chip `National Semiconductor LM75' (confidence: 3)
- Bus `s3c2410-i2c'
  Busdriver`UNKNOWN', I2C address 0x4a
  Chip `National Semiconductor LM75' (confidence: 3)
- Bus `s3c2410-i2c'
  Busdriver`UNKNOWN', I2C address 0x4b
  Chip `National Semiconductor LM75' (confidence: 3)
- Bus `s3c2410-i2c'
  Busdriver`UNKNOWN', I2C address 0x4c
  Chip `National Semiconductor LM75' (confidence: 3)
- Bus `s3c2410-i2c'
  Busdriver`UNKNOWN', I2C address 0x4d
  Chip `National Semiconductor LM75' (confidence: 3)
- Bus `s3c2410-i2c'
  Busdriver`UNKNOWN', I2C address 0x4e
  Chip `National Semiconductor LM75' (confidence: 3)
- Bus `s3c2410-i2c'
  Busdriver`UNKNOWN', I2C address 0x4f
  Chip `National Semiconductor LM75' (confidence: 3)

**Comment by mdrjr** [comment]
Sure.. LM75 for U3 right?

**Comment by mdrjr** [comment]
Above is the commit that fixes it..
Its added.. make sure to poke around of the /sys _sysfs_ to probe the sensor.

I'm closing this.. within the next 4 hours a new build should be available.
