### ISSUE TITLE
ASIX 88179 dongle crashes XU under certain traffic loads

### ISSUE THREAD

**Issue by declanmalone** [hardkernel/linux#51]
With XU configured as a router with both integrated NIC and Gigabit dongle, making a kernel with distcc causes the XU to shut down completely with no log messages. Sustained test with iperf does not cause the machine to crash.
Tested with master distcc host on 100Mbs side and two slave machines on the Gbit side.
More info on the forums: http://forum.odroid.com/viewtopic.php?f=73&t=5188

**Comment by VittGam** [comment]
I think you made a mistake in the title... The Asix 88179 is the USB3 Gigabit Ethernet, not the Wifi card.

Anyway I'm also experiencing issues with freezes that seem related to both CPU power/cluster switching and the Gigabit Ethernet... And I think they're related. See http://forum.odroid.com/viewtopic.php?f=61&t=5376 for my problem and a kernel log just before a crash.
