### ISSUE TITLE
Problem Buildingwith Yocto due to wrong symlink

### ISSUE THREAD

**Issue by MarkusEich** [hardkernel/linux#59]
Dear all,

I am working to build the kernel using the yocto embedded toolchain https://www.yoctoproject.org. It does not work out of the box because the build process in Kernel 3.4 creates a recursive symbolic link while building /drivers/gpu/arm/mali400/ump

The reason for this behaviour in the 3.4.y kernel is  the commit 73341c84ade21b97091b0289a9ddfc00900c038b where arch-release is added. It was removed in commit 9a3fbdc18fca5adc117ad6b505a625859adb969e.

The following path fixes this issue.

--- linux/drivers/gpu/arm/mali400/ump/Kbuild    2014-07-30 15:44:03.984805492 +0200
+++ linux/drivers/gpu/arm/mali400/ump/Kbuild    2014-07-30 15:44:39.609139070 +0200
@@ -21,7 +21,7 @@
 else
 # Link arch to the selected arch-config directory
 $(shell [ -L $(src)/arch ] && rm $(src)/arch)
-$(shell ln -sf arch-$(CONFIG) $(src)/arch)
+$(shell ln -sf $(src)/arch-$(CONFIG) $(src)/arch)
 $(shell touch $(src)/arch/config.h)
 endif

Maybe add this fix to the master branch?

**Comment by mdrjr** [comment]
We can safely ignore MP400 drivers on XU kernel...
If you want to submit it as a PR I'll merge it
