### ISSUE TITLE
undefined reference to `exynos_enter_aftr'

### ISSUE THREAD

**Issue by alphaonex86** [hardkernel/linux#64]
Hello, I have with vanilla 3.17.0:

arch/arm/mach-exynos/built-in.o: In function `.LANCHOR1':
:(.data+0x74): undefined reference to`exynos_enter_aftr'
My config file:
http://files.first-world.info/temp/config.xz
If already patched, can you say me the patch number. And say me what is the config responsive of that's.
My target it's have low power server node.

Thanks for your work on mainline, greate work. Cheers,

**Comment by alphaonex86** [comment]
Why closed without comment?

**Comment by mdrjr** [comment]
Lets starts:
1. I don't see any branch on this github with 3.17
2. You didn't posted your defconfig
3. If you are using vanilla you should complain on linux-samsung ML not here as this is Hardkernel not Samsung
4. You didn't said what compiler you was using

Want me to continue the list ?

**Comment by alphaonex86** [comment]
1) I presume same with other version, but only the 3.17 have work here
2) work with def config, the problem seam be CONFIG_SUSPEND=n
3) ok, thanks for the info
4) gcc version 4.7.4
