### ISSUE TITLE
Typo in ASV tables

### ISSUE THREAD

**Issue by punitagrawal** [hardkernel/linux#68]
While working on Odroid XU3, I noticed a typo in the ASV tables which would cause cpufreq to not work correctly on boards with ASV=5.

The typo is in https://github.com/hardkernel/linux/blob/odroidxu3-3.10.y/arch/arm/mach-exynos/include/mach/asv-exynos5422_evt0.h#L347. '98750' should be '987500', i.e., a missing zero. This leads to incorrect voltage being assigned to that frequency which then fails sanity checking in code and causes cpufreq to misbehave.

Please let me know if you'd like any more details.

Thanks.

**Comment by mdrjr** [comment]
So.. Pull request with a fix or should I just go ahead and fix it ?

**Comment by punitagrawal** [comment]
I've now sent a pull request (#69).
