### ISSUE TITLE
Symbol collision on linking

### ISSUE THREAD

**Issue by twitch153** [hardkernel/linux#73]
When compiling the kernel for the Odroid-XU3 on branch 3.10.y if you have the right configuration you will run into this while trying link the binary:

  LD      arch/arm/mach-exynos/built-in.o
arch/arm/mach-exynos/secmem.o: In function `exynos_ion_sync_for_device':
secmem.c:(.text+0xd4): multiple definition of`exynos_ion_sync_for_device'
arch/arm/mach-exynos/mach-odroid-xu3.o:mach-odroid-xu3.c:(.text+0x0): first defined here
arch/arm/mach-exynos/secmem.o: In function `exynos_ion_sync_for_cpu':
secmem.c:(.text+0xec): multiple definition of`exynos_ion_sync_for_cpu'
arch/arm/mach-exynos/mach-odroid-xu3.o:mach-odroid-xu3.c:(.text+0x18): first defined here
scripts/Makefile.build:387: recipe for target 'arch/arm/mach-exynos/built-in.o' failed
make[1]: **\* [arch/arm/mach-exynos/built-in.o] Error 1
Makefile:797: recipe for target 'arch/arm/mach-exynos' failed

A simple fix would be give a static context to the functions at https://github.com/hardkernel/linux/blob/odroidxu3-3.10.y/include/linux/exynos_ion.h#L131

The error occurs because both .c files bring in the exynos_ion.h header file and the void functions are declared globally. So making them static shouldn't be an issue when it comes to symbol resolution by the linker. I've tested this fix myself and can confirm it builds properly as it should.

**Comment by Reneg973** [comment]
I've modified the mach-odroid-xu3.c so, that the ion header is just included if required:

#ifdef CONFIG_ION_EXYNOS
#include  &lt;linux/exynos_ion.h&gt;
#endif

**Comment by mdrjr** [comment]
send a PR with the changes and we'll happily accept it.
