### ISSUE TITLE
odroidc needs to export fiq_bridge_pulse_trigger from plat-meson/fiq_bridge.c

### ISSUE THREAD

**Issue by sdrsdr** [hardkernel/linux#79]
This symbol is used in staging drivers that are set to build as modules and this breaks the build.

**Comment by sdrsdr** [comment]
Also I'm unable to boot with the latest git sources  on odroidc1 following   the instructions from the wiki  odroid.com/dokuwiki/doku.php?id=en:c1_building_kernel

**Comment by mdrjr** [comment]
Pushed a fix for the not booting issue..
As for the missing symbol I don't have this error building.
Check your toolchain/whatever...

**Comment by sdrsdr** [comment]
I'm still unable to boot from sdcard
