### ISSUE TITLE
amlogic/spicc bits per word > 8

### ISSUE THREAD

**Issue by farindk** [hardkernel/linux#87]
SPI transfers with word sizes > 8 bits are not supported correctly. While you can set larger word sizes, only the 8 LSBs are filled with data. I.e., sending out 4 bytes of data as a 32 bit word does not result in a 32 bit word, but in four 32 bit words with 8 bit of data in each.

Seems that cases with word size != 8 is not considered in spicc_hw_xfer().
The TXDATA register is 32bit wide, but always filled with 8 bit data.

**Comment by mdrjr** [comment]
Issues should be posted on the forums.
